name: premake4-ubuntu-codeblocks

on:
  workflow_dispatch:
  push:
    paths:
      - 'projects/project-*/**'
      - 'codeblocks/**'
      - '.github/workflows/premake4-ubuntu-codeblocks.yml'
      - '!**/*.md'
  pull_request:
    paths:
      - 'projects/project-*/**'
      - 'codeblocks/**'
      - '.github/workflows/premake4-ubuntu-codeblocks.yml'
      - '!**/*.md'

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: apt-get update
      run: sudo apt-get update -y

    - name: apt-get install premake4
      run: sudo apt-get install -y premake4

    - name: apt-get install -y codeblocks
      run: sudo apt-get install -y codeblocks

    - name: codeblocks's default configuration
      run: |
        mkdir -p ~/.config/codeblocks
        cp codeblocks/default.conf ~/.config/codeblocks/

    - name: test projects
      timeout-minutes: 5 # tends to not stop properly in case of failure
      uses: GabrielBB/xvfb-action@v1 # fake X-server as codeblocks requires displays :/
      with:
        run: ./test_projects.sh premake4 codeblocks
