name: premake5-ubuntu-codelite

on:
  workflow_dispatch:
  push:
    paths:
      - 'projects/project-*/**'
      - 'codelite/**'
      - '.github/workflows/premake5-ubuntu-codelite.yml'
      - '!**/*.md'
      - '!**/unsupported_by_*'
  pull_request:
    paths:
      - 'projects/project-*/**'
      - 'codelite/**'
      - '.github/workflows/premake5-ubuntu-codelite.yml'
      - '!**/*.md'
      - '!**/unsupported_by_*'

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: checkout premake5
      uses: actions/checkout@v2
      with:
          repository: premake/premake-core
          path: premake-build
    - name: Build premake5
      run: |
        cd premake-build
        make -f Bootstrap.mak linux CONFIG=release
        cp bin/release/premake5 ../
        cd ..
        rm -Rf premake-build

    - name: apt-get update
      run: sudo apt-get update -y

    - name: sudo apt-get install -y codelite
      run: sudo apt-get install -y codelite

    - name: test projects default(clang)
      run: PATH=$PATH:`pwd` ./test_projects.sh premake5 projects codelite

    - name: test projects gcc
      run: PATH=$PATH:`pwd` ./test_projects.sh premake5 projects codelite --cc=gcc

    - name: test projects clang
      run: PATH=$PATH:`pwd` ./test_projects.sh premake5 projects codelite --cc=clang
