name: premake5-ubuntu-gmake

on:
  workflow_dispatch:
  push:
    paths:
      - 'projects/project-*/**'
      - '.github/workflows/premake5-ubuntu-gmake.yml'
      - '!**/*.md'
      - '!projects/**/unsupported_by_*'
      - '!**/premake4.lua'
      - 'projects/**/unsupported_by_gmake'
      - 'projects/**/unsupported_by_premake5_gmake'

  pull_request:
    paths:
      - 'projects/project-*/**'
      - '.github/workflows/premake5-ubuntu-gmake.yml'
      - '!**/*.md'
      - '!projects/**/unsupported_by_*'
      - '!**/premake4.lua'
      - 'projects/**/unsupported_by_gmake'
      - 'projects/**/unsupported_by_premake5_gmake'

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: checkout premake5
      uses: actions/checkout@v4
      with:
          repository: premake/premake-core
          path: premake-build

    - name: Build premake5
      run: |
        cd premake-build
        make -f Bootstrap.mak linux CONFIG=release
        cp bin/release/premake5 ../
        cd ..
        rm -Rf premake-build

    - name: make --version
      run: make --version

    - name: test projects default(gcc)
      run: PATH=$PATH:`pwd` python3 ./test_projects.py premake5 projects gmake

    - name: test projects gcc
      run: PATH=$PATH:`pwd` python3 ./test_projects.py premake5 projects gmake --cc=gcc

    - name: test projects clang
      run: PATH=$PATH:`pwd` python3 ./test_projects.py premake5 projects gmake --cc=clang
