name: premake5-qt5-ubuntu-codeblocks

on:
  workflow_dispatch:
  push:
    paths:
      - 'projects-qt/project-*/**'
      - 'codeblocks/**'
      - '.github/workflows/premake5-qt5-ubuntu-codeblocks.yml'
      - '!**/*.md'
      - '!**/unsupported_by_*'
  pull_request:
    paths:
      - 'projects-qt/project-*/**'
      - 'codeblocks/**'
      - '.github/workflows/premake5-qt5-ubuntu-codeblocks.yml'
      - '!**/*.md'
      - '!**/unsupported_by_*'

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: apt-get update
      run: sudo apt-get update -y

    - name: checkout premake5
      uses: actions/checkout@v2
      with:
          repository: premake/premake-core
          path: premake-build
    - name: Build premake5
      run: |
        cd premake-build
        make -f Bootstrap.mak linux CONFIG=release
        cp bin/release/premake5 ../
        cd ..
        rm -Rf premake-build
        echo `pwd` >> $GITHUB_PATH

    - name: add premake codeblocks module
      run: |
        echo "require 'submodules/premake-codeblocks/codeblocks'" >> premake-system.lua

    - name: add premake qt module
      run: |
        echo "require 'submodules/premake-qt/qt'" >> premake-system.lua

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: cache-ubuntu-Qt5.15.0

    - name: Installing Qt5.15.0 ubuntu
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.0'
        cached: ${{ steps.cache-qt.outputs.cache-hit }}

    - name: apt-get install -y codeblocks
      run: sudo apt-get install -y codeblocks

    - name: codeblocks's default configuration
      run: |
        mkdir -p ~/.config/codeblocks
        cp codeblocks/default.conf ~/.config/codeblocks/

    - name: set path
      run: |
         echo PATH=$PATH:`pwd`
         echo PATH=$PATH:`pwd` >> $GITHUB_ENV
         echo QT_DIR=$Qt5_Dir
         echo QT_DIR=$Qt5_Dir >> $GITHUB_ENV

    - name: test projects default(gcc)
      timeout-minutes: 5 # tends to not stop properly in case of failure
      uses: GabrielBB/xvfb-action@v1 # fake X-server as Codeblocks and Qt Widget require displays :/
      with: # Cannot use environment variable ($Qt5_Dir) in command line, so use environment variable (QT_DIR) or its hardcoded value
        run:  ./test_projects.sh premake5 projects-qt codeblocks #--qt-root=/home/runner/work/premake-sample-projects/Qt/5.15.0/gcc_64
