name: premake4-ubuntu-codelite

on:
  workflow_dispatch:
  push:
    paths:
      - 'projects/project-*/**'
      - 'codelite/**'
      - '.github/workflows/premake4-ubuntu-codelite.yml'
      - '!**/*.md'
      - '!**/unsupported_by_*'
  pull_request:
    paths:
      - 'projects/project-*/**'
      - 'codelite/**'
      - '.github/workflows/premake4-ubuntu-codelite.yml'
      - '!**/*.md'
      - '!**/unsupported_by_*'

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: apt-get update
      run: sudo apt-get update -y

    - name: apt-get install premake4
      run: sudo apt-get install -y premake4

    - name: sudo apt-get install -y codelite
      run: sudo apt-get install -y codelite

    - name: test projects default(clang)
      run: ./test_projects.sh premake4 codelite

    - name: test projects gcc
      run: ./test_projects.sh premake4 codelite --cc=gcc

    - name: test projects clang
      run: ./test_projects.sh premake4 codelite --cc=clang
