name: premake5-qt5-ubuntu-codeblocks

on:
  workflow_dispatch:
  push:
    paths:
      - 'projects-qt/project-*/**'
      - 'codeblocks/**'
      - '.github/workflows/premake5-qt5-ubuntu-codeblocks.yml'
      - '!**/*.md'
      - '!projects-qt/**/unsupported_by_*'
      - '!**/premake4.lua'
      - 'projects-qt/**/unsupported_by_codeblocks'
      - 'submodules/premake-codeblocks'
      - 'submodules/premake-qt'

  pull_request:
    paths:
      - 'projects-qt/project-*/**'
      - 'codeblocks/**'
      - '.github/workflows/premake5-qt5-ubuntu-codeblocks.yml'
      - '!**/*.md'
      - '!projects-qt/**/unsupported_by_*'
      - '!**/premake4.lua'
      - 'projects-qt/**/unsupported_by_codeblocks'
      - 'submodules/premake-codeblocks'
      - 'submodules/premake-qt'

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: apt-get update
      run: sudo apt-get update -y

    - name: checkout premake5
      uses: actions/checkout@v3
      with:
          repository: premake/premake-core
          path: premake-build
    - name: Build premake5
      run: |
        cd premake-build
        make -f Bootstrap.mak linux CONFIG=release
        cp bin/release/premake5 ../
        cd ..
        rm -Rf premake-build
        echo `pwd` >> $GITHUB_PATH

    - name: add premake codeblocks module
      run: |
        echo "require 'submodules/premake-codeblocks/codeblocks'" >> premake-system.lua

    - name: add premake qt module
      run: |
        echo "require 'submodules/premake-qt/qt'" >> premake-system.lua

    - name: Installing Qt5.15.0 ubuntu
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.0'
        cache: true
        cache-key-prefix: 'qt-action-5.15.0_ubuntu'

    - name: apt-get install -y codeblocks
      run: sudo apt-get install -y codeblocks

    - name: codeblocks's default configuration
      run: |
        mkdir -p ~/.config/codeblocks
        cp codeblocks/default.conf ~/.config/codeblocks/

    - name: set path
      run: |
         echo PATH=$PATH:`pwd`
         echo PATH=$PATH:`pwd` >> $GITHUB_ENV
         echo QT_DIR=$Qt5_Dir
         echo QT_DIR=$Qt5_Dir >> $GITHUB_ENV

    - name: install libxkbcommon-x11-0 # display dependency
      run: sudo apt-get install libxkbcommon-x11-0

    - name: test projects default(gcc)
      timeout-minutes: 5 # tends to not stop properly in case of failure
      run: | # fake X-server as Qt widget requires displays :/
        # Cannot use environment variable ($Qt5_Dir) in command line, so use environment variable (QT_DIR) or its hardcoded value
        xvfb-run -a ./test_projects.sh premake5 projects-qt codeblocks #--qt-root=/home/runner/work/premake-sample-projects/Qt/5.15.0/gcc_64
