name: premake5-windows-ninja

on:
  workflow_dispatch:
  push:
    paths:
      - 'projects/project-*/**'
      - '.github/workflows/premake5-windows-ninja.yml'
      - '!**/*.md'
      - '!projects/**/unsupported_by_*'
      - '!**/premake4.lua'
      - 'projects/**/unsupported_by_ninja'
      - 'submodules/premake-ninja'

  pull_request:
    paths:
      - 'projects/project-*/**'
      - '.github/workflows/premake5-windows-ninja.yml'
      - '!**/*.md'
      - '!projects/**/unsupported_by_*'
      - '!**/premake4.lua'
      - 'projects/**/unsupported_by_ninja'
      - 'submodules/premake-ninja'

jobs:
  windows:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: checkout premake5
      uses: actions/checkout@v3
      with:
        repository: premake/premake-core
        path: premake-build

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1.3

    - name: Build premake5
      run: |
        $vcvarall_path = vswhere -find VC\Auxiliary\Build\vcvarsall.bat
        cmd.exe /c "call ""$vcvarall_path"" x86_amd64 && cd premake-build && nmake -f Bootstrap.mak MSDEV=vs2022 windows-msbuild PLATFORM=Win32 CONFIG=release && cp bin/release/premake5.exe ../"

    - name: install ninja
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: ninja --version
      run: ninja --version

    - name: add premake ninja module
      run: |
        echo "require 'submodules/premake-ninja/ninja'" >> premake-system.lua

    - name: Add cl.exe to PATH # microsoft/setup-msbuild doesn't add it :(
      uses: ilammy/msvc-dev-cmd@v1

#    - name: test projects default(msc-v142) # Visual Studio 2019 (version mismatch is not that important, only cl.exe is called)
#      run: |
#        #"C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
#        echo $PATH
#        PATH=$PATH:`pwd` ./test_projects.sh premake5 projects ninja
#      shell: bash

    - name: test projects msc-v143 # Visual Studio 2022
      run: |
        #"C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
        echo $PATH
        PATH=$PATH:`pwd` ./test_projects.sh premake5 projects ninja --cc=msc-v143
      shell: bash

#    - name: test projects gcc
#      run: |
#        echo $PATH
#        PATH=$PATH:`pwd` ./test_projects.sh premake5 projects ninja --cc=gcc
#      shell: bash
