name: premake5-ubuntu-qmake

on:
  workflow_dispatch:
  push:
    paths:
      - 'projects/project-*/**'
      - '.github/workflows/premake5-ubuntu-qmake.yml'
      - '!**/*.md'
      - '!projects/**/unsupported_by_*'
      - '!**/premake4.lua'
      - 'projects/**/unsupported_by_qmake'
      - 'projects/**/unsupported_by_premake5_qmake'
      - 'submodules/premake-qmake'

  pull_request:
    paths:
      - 'projects/project-*/**'
      - '.github/workflows/premake5-ubuntu-qmake.yml'
      - '!**/*.md'
      - '!projects/**/unsupported_by_*'
      - '!**/premake4.lua'
      - 'projects/**/unsupported_by_qmake'
      - 'projects/**/unsupported_by_premake5_qmake'
      - 'submodules/premake-qmake'

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: checkout premake5
      uses: actions/checkout@v4
      with:
          repository: premake/premake-core
          path: premake-build

    - name: Build premake5
      run: |
        cd premake-build
        make -f Bootstrap.mak linux CONFIG=release
        cp bin/release/premake5 ../
        cd ..
        rm -Rf premake-build

    - name: add premake qmake module
      run: |
        echo "require 'submodules/premake-qmake/qmake'" >> premake-system.lua

    - name: Installing Qt5.15.0 ubuntu
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.0'
        cache: true
        cache-key-prefix: 'qt-action-5.15.0_ubuntu'

    - name: test qmake
      run: qmake --version

    - name: test projects default(gcc)
      run: PATH=$PATH:`pwd` python3 ./test_projects.py premake5 projects qmake

    - name: test projects gcc
      run: PATH=$PATH:`pwd` python3 ./test_projects.py premake5 projects qmake --cc=gcc

    - name: test projects clang
      run: PATH=$PATH:`pwd` python3 ./test_projects.py premake5 projects qmake --cc=clang
