name: premake4-ubuntu-gmake

on:
  workflow_dispatch:
  push:
    paths:
      - 'project-*/**'
      - '.github/workflows/premake4-ubuntu-gmake.yml'
      - '!**/*.md'
  pull_request:
    paths:
      - 'project-*/**'
      - '.github/workflows/premake4-ubuntu-gmake.yml'
      - '!**/*.md'

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: apt-get install premake4
      run: sudo apt-get install -y premake4

    - name: test projects
      run: ./test_projects.sh premake4 gmake
