name: premake5-ubuntu-ninja

on:
  workflow_dispatch:
  push:
    paths:
      - 'projects/project-*/**'
      - '.github/workflows/premake5-ubuntu-ninja.yml'
      - '!**/*.md'
      - '!projects/**/unsupported_by_*'
      - '!**/premake4.lua'
      - 'projects/**/unsupported_by_ninja'
      - 'submodules/premake-ninja'

  pull_request:
    paths:
      - 'projects/project-*/**'
      - '.github/workflows/premake5-ubuntu-ninja.yml'
      - '!**/*.md'
      - '!projects/**/unsupported_by_*'
      - '!**/premake4.lua'
      - 'projects/**/unsupported_by_ninja'
      - 'submodules/premake-ninja'

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: checkout premake5
      uses: actions/checkout@v3
      with:
          repository: premake/premake-core
          path: premake-build

    - name: Build premake5
      run: |
        cd premake-build
        make -f Bootstrap.mak linux CONFIG=release
        cp bin/release/premake5 ../
        cd ..
        rm -Rf premake-build

    - name: apt-get update
      run: sudo apt-get update -y

    - name: apt-get install ninja-build
      run: |
        sudo apt-get install -y ninja-build

    - name: ninja --version
      run: ninja --version

    - name: add premake ninja module
      run: |
        echo "require 'submodules/premake-ninja/ninja'" >> premake-system.lua

    - name: test projects default(gcc)
      run: PATH=$PATH:`pwd` ./test_projects.sh premake5 projects ninja

    - name: test projects gcc
      run: PATH=$PATH:`pwd` ./test_projects.sh premake5 projects ninja --cc=gcc

    - name: test projects clang
      run: PATH=$PATH:`pwd` ./test_projects.sh premake5 projects ninja --cc=clang
