name: premake5-windows-msvc-2019

on:
  workflow_dispatch:
  push:
    paths:
      - 'projects/project-*/**'
      - '.github/workflows/premake5-windows-msvc-2019.yml'
      - '!**/*.md'
      - '!projects/**/unsupported_by_*'
      - '!**/premake4.lua'
      - 'projects/**/unsupported_by_vs2019'

  pull_request:
    paths:
      - 'projects/project-*/**'
      - '.github/workflows/premake5-windows-msvc-2019.yml'
      - '!**/*.md'
      - '!projects/**/unsupported_by_*'
      - '!**/premake4.lua'
      - 'projects/**/unsupported_by_vs2019'

jobs:
  windows:
    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: checkout premake5
      uses: actions/checkout@v3
      with:
        repository: premake/premake-core
        path: premake-build

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1.3

    - name: Build premake5
      run: |
        $vcvarall_path = vswhere -find VC\Auxiliary\Build\vcvarsall.bat
        cmd.exe /c "call ""$vcvarall_path"" x86_amd64 && cd premake-build && nmake -f Bootstrap.mak MSDEV=vs2019 windows-msbuild PLATFORM=Win32 CONFIG=release && cp bin/release/premake5.exe ../"

    - name: test projects (default=msc)
      run: |
        #"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
        PATH=$PATH:`pwd` python3 ./test_projects.py premake5 projects vs2019
      shell: bash

    - name: test projects (clang)
      run: |
        PATH=$PATH:`pwd` python3 ./test_projects.py premake5 projects vs2019 --cc=clang
      shell: bash
