name: premake5-ubuntu-codeblocks

on:
  workflow_dispatch:
  push:
    paths:
      - 'projects/project-*/**'
      - 'codeblocks/**'
      - '.github/workflows/premake5-ubuntu-codeblocks.yml'
      - '!**/*.md'
  pull_request:
    paths:
      - 'projects/project-*/**'
      - 'codeblocks/**'
      - '.github/workflows/premake5-ubuntu-codeblocks.yml'
      - '!**/*.md'

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: apt-get update
      run: sudo apt-get update -y

    - name: checkout premake5
      uses: actions/checkout@v2
      with:
          repository: premake/premake-core
          path: premake-build
    - name: Build premake5
      run: |
        cd premake-build
        make -f Bootstrap.mak linux CONFIG=release
        cp bin/release/premake5 ../
        cd ..
        rm -Rf premake-build
        echo `pwd` >> $GITHUB_PATH

    - name: add premake codeblocks module
      run: |
        echo "require 'submodules/premake-codeblocks/codeblocks'" >> premake-system.lua

    - name: apt-get install -y codeblocks
      run: sudo apt-get install -y codeblocks

    - name: codeblocks's default configuration
      run: |
        mkdir -p ~/.config/codeblocks
        cp codeblocks/default.conf ~/.config/codeblocks/

    - name: test projects
      timeout-minutes: 5 # tends to not stop properly in case of failure
      uses: GabrielBB/xvfb-action@v1 # fake X-server as codeblocks requires displays :/
      with:
        run: ./test_projects.sh premake5 codeblocks
