name: premake5-ubuntu-codeblocks

on:
  workflow_dispatch:
  push:
    paths:
      - 'projects/project-*/**'
      - 'codeblocks/**'
      - '.github/workflows/premake5-ubuntu-codeblocks.yml'
      - '!**/*.md'
      - '!**/unsupported_by_*'
  pull_request:
    paths:
      - 'projects/project-*/**'
      - 'codeblocks/**'
      - '.github/workflows/premake5-ubuntu-codeblocks.yml'
      - '!**/*.md'
      - '!**/unsupported_by_*'

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: apt-get update
      run: sudo apt-get update -y

    - name: checkout premake5
      uses: actions/checkout@v3
      with:
          repository: premake/premake-core
          path: premake-build
    - name: Build premake5
      run: |
        cd premake-build
        make -f Bootstrap.mak linux CONFIG=release
        cp bin/release/premake5 ../
        cd ..
        rm -Rf premake-build
        echo `pwd` >> $GITHUB_PATH

    - name: add premake codeblocks module
      run: |
        echo "require 'submodules/premake-codeblocks/codeblocks'" >> premake-system.lua

    - name: apt-get install -y codeblocks
      run: sudo apt-get install -y codeblocks

    - name: codeblocks's default configuration
      run: |
        mkdir -p ~/.config/codeblocks
        cp codeblocks/default.conf ~/.config/codeblocks/

    - name: test projects default(gcc)
      timeout-minutes: 5 # tends to not stop properly in case of failure
      run: | # fake X-server as codeblocks requires displays :/
        xvfb-run -a ./test_projects.sh premake5 projects codeblocks

    - name: test projects gcc
      timeout-minutes: 5 # tends to not stop properly in case of failure
      run: | # fake X-server as codeblocks requires displays :/
        xvfb-run -a ./test_projects.sh premake5 projects codeblocks --cc=gcc

    - name: test projects clang
      timeout-minutes: 5 # tends to not stop properly in case of failure
      run: | # fake X-server as codeblocks requires displays :/
        xvfb-run -a ./test_projects.sh premake5 projects codeblocks --cc=clang
