name: premake5-qt5-windows-msvc-2019

on:
  workflow_dispatch:
  push:
    paths:
      - 'projects-qt/project-*/**'
      - '.github/workflows/premake5-qt5-windows-msvc-2019.yml'
      - '!**/*.md'
      - '!projects-qt/**/unsupported_by_*'
      - '!**/premake4.lua'
      - 'projects-qt/**/unsupported_by_vs2019'
      - 'projects-qt/**/unsupported_by_premake5_vs2019'
      - 'submodules/premake-qt'

  pull_request:
    paths:
      - 'projects-qt/project-*/**'
      - '.github/workflows/premake5-qt5-windows-msvc-2019.yml'
      - '!**/*.md'
      - '!projects-qt/**/unsupported_by_*'
      - '!**/premake4.lua'
      - 'projects-qt/**/unsupported_by_vs2019'
      - 'projects-qt/**/unsupported_by_premake5_vs2019'
      - 'submodules/premake-qt'

jobs:
  windows:
    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: checkout premake5
      uses: actions/checkout@v4
      with:
        repository: premake/premake-core
        path: premake-build

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build premake5
      run: |
        $vcvarall_path = vswhere -find VC\Auxiliary\Build\vcvarsall.bat
        cmd.exe /c "call ""$vcvarall_path"" x86_amd64 && cd premake-build && nmake -f Bootstrap.mak MSDEV=vs2019 windows-msbuild PLATFORM=Win32 CONFIG=release && cp bin/release/premake5.exe ../"

    - name: Installing Qt - 5.15.0 win64_msvc2019_64
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.0'
        arch: win64_msvc2019_64
        cache: true
        cache-key-prefix: 'qt-action-5.15.0_win64_msvc2019_64'

    - name: test projects
      run: |
        PATH=$PATH:`pwd` python3 ./test_projects.py premake5 projects-qt vs2019 --qt-root=$Qt5_Dir
      shell: bash
