name: premake5-ubuntu-cmake

on:
  workflow_dispatch:
  push:
    paths:
      - 'projects/project-*/**'
      - '.github/workflows/premake5-ubuntu-cmake.yml'
      - '!**/*.md'
      - '!**/unsupported_by_*'
  pull_request:
    paths:
      - 'projects/project-*/**'
      - '.github/workflows/premake5-ubuntu-cmake.yml'
      - '!**/*.md'
      - '!**/unsupported_by_*'

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: checkout premake5
      uses: actions/checkout@v3
      with:
          repository: premake/premake-core
          path: premake-build

    - name: Build premake5
      run: |
        cd premake-build
        make -f Bootstrap.mak linux CONFIG=release
        cp bin/release/premake5 ../
        cd ..
        rm -Rf premake-build

    - name: cmake --version
      run: cmake --version

    - name: add premake cmake module
      run: |
        echo "require 'submodules/premake-cmake/cmake'" >> premake-system.lua

    - name: test projects
      run: PATH=$PATH:`pwd` ./test_projects.sh premake5 projects cmake
