name: ubuntu-gmake

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Test Simple
      run: |
        premake5 --file="project-00/premake5.lua" gmake
        cd solution/project-00/gmake
        make
      continue-on-error: true

    - name: Test BuildOptions
      run: |
        premake5 --file="project-01/premake5.lua" gmake
        cd solution/project-01/gmake
        make
      continue-on-error: true

    - name: Test LinkOptions
      run: |
        premake5 --file="project-02/premake5.lua" gmake
        cd solution/project-02/gmake
        make
      continue-on-error: true
